geoserver:
  build: ./geoserver_mock
  environment:
    DATADIR_PATH: /opt/geoserver_data_dir
  volumes:
    - geoserver_datadir:/opt/geoserver_data_dir:rw

sync:
  #build: ./sync
  image: fvanderbiest/volume-git-backup
  environment:
    WATCH_FILE: global.xml
    SLEEPING_TIME: 5
    COMMIT_MESSAGE: printf "updateSequence "; grep updateSequence global.xml|sed -e 's#.*ce>\(.*\)</up.*#\1#'
    USERNAME: fvanderbiest
    EMAIL: francois.vanderbiest@gmail.com
    PUSH: 'true'
    REMOTE_NAME: origin
    REMOTE_URL: https://github.com/fvanderbiest/playground
    TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  volumes:
    - geoserver_datadir:/var/local/data:rw
